# Generated by Django 4.1.2 on 2022-11-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Post',
        ),
    ]
