# Generated by Django 4.1.2 on 2022-11-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsite', '0002_rename_images_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Review',
        ),
    ]
