# Generated by Django 4.1.2 on 2022-11-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsite', '0003_rename_post_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_added']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='textbody',
        ),
        migrations.AddField(
            model_name='review',
            name='preview',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
