# Generated by Django 4.1.2 on 2022-11-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsite', '0007_post_remove_comment_review_delete_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_added',
        ),
    ]
