# Generated by Django 4.1.2 on 2022-11-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsite', '0008_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
    ]
