# Generated by Django 4.1.2 on 2022-11-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsite', '0009_remove_post_body_remove_post_intro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='topic',
        ),
    ]
