# Generated by Django 4.1.2 on 2022-11-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsite', '0010_rename_post_topic_rename_post_comment_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
