# Generated by Django 4.1.2 on 2022-11-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsite', '0013_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
